const namePattern = /[a-z-]+/;

module.exports = {
  "extends": "stylelint-config-standard",
  "plugins": [
    "stylelint-order",
    "stylelint-scss",
  ],
  "rules": {
    "at-rule-no-vendor-prefix": true,
    "block-closing-brace-newline-after": ["always", {
      "ignoreAtRules": ["/^[a-z]*-mixin/", "include"],
    }],
    "block-closing-brace-newline-before": "always",
    "block-opening-brace-newline-after": "always",
    "block-opening-brace-space-before": "always",
    "color-hex-length": "long",
    "color-named": "never",
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-semicolon-newline-after": "always",
    "declaration-colon-newline-after": null,
    "declaration-colon-space-after": "always",
    "declaration-no-important": true,
    "declaration-property-value-blacklist": {
        "/^border/": ["none"],
        "padding": ["auto"],
    },
    "font-family-name-quotes": "always-unless-keyword",
    "font-weight-notation": "numeric",
    "function-url-no-scheme-relative": true,
    "function-url-quotes": "always",
    "indentation": 4,
    "max-nesting-depth": 3,
    "media-feature-name-no-vendor-prefix": true,
    "property-no-unknown": true,
    "property-no-vendor-prefix": true,
    "rule-empty-line-before": ["always", {
      "except": ["first-nested"],
      "ignore": ["after-comment"],
    }],
    "selector-attribute-quotes": "always",
    "selector-max-compound-selectors": 3,
    "selector-no-id": true,
    "selector-no-qualifying-type": [true, {
      "ignore": ["attribute"],
    }],
    "selector-no-universal": true,
    "selector-no-vendor-prefix": true,
    "selector-type-no-unknown": [true, {
      "ignoreTypes": ["/^%/"],
    }],
    "string-quotes": "single",
    "time-min-milliseconds": 100,
    "value-keyword-case": "lower",
    "value-no-vendor-prefix": true,

    "order/declaration-block-properties-alphabetical-order": true,

    "scss/at-extend-no-missing-placeholder": true,
    "scss/at-function-pattern": namePattern,
    "scss/at-mixin-argumentless-call-parentheses": "always",
    "scss/at-mixin-pattern": namePattern,
    "scss/dollar-variable-colon-space-after": "always",
    "scss/dollar-variable-colon-space-before": "never",
    "scss/dollar-variable-pattern": namePattern,
    "scss/double-slash-comment-whitespace-inside": "always",
    "scss/operator-no-unspaced": true,
    "scss/percent-placeholder-pattern": namePattern,
    "scss/selector-no-redundant-nesting-selector": true,
  },
};
